### ISSUE TITLE
Installation of plugin fails

### ISSUE THREAD

**Issue by mishschmid** [ahmadawais/WP-REST-Allow-All-CORS#1]
Hi, I'm using Wordpress 4.8. When I try to install the plugin, I get the following error:

Plugin could not be activated because it triggered a fatal error.

Parse error: syntax error, unexpected T_FUNCTION in /home/www/web183/html/wp-content/plugins/WP-REST-Allow-All-CORS-master/plugin.php on line 35

**Comment by ahmadawais** [comment]
@RustyRomeo Can you try it out on a new install. Doesn't seem to be an issue at my end.

**Comment by mishschmid** [comment]
@ahmadawais I found the issue. Another plugin was breaking the REST API. Sorry the circumstances. Closing this issue.

**Comment by ahmadawais** [comment]
Glad I could help :) @RustyRomeo Care to star the repo to show support :)
